artifacts_root: artifacts



data_ingestion: #always make sure for the indentations otherwise it will give an error.
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/ravina029/datasets/main/cat-dog-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

  
  